(source melpa)
(source gnu)
(depends-on "nyan-mode")
(depends-on "auto-minor-mode")
(depends-on "vue-html-mode")
(depends-on "python-black")
(depends-on "company-jedi")
(depends-on "jinja2-mode")
(depends-on "htmlize")
(depends-on "cmake-mode")
(depends-on "auto-complete")
(depends-on "json-mode")
(depends-on "yaml-mode")
(depends-on "company")
(depends-on "markdown-mode")
(depends-on "eclim")
(depends-on "gradle-mode")
(depends-on "company-emacs-eclim")
(depends-on "terraform-mode")
(depends-on "magit")
(depends-on "pianobar")
(depends-on "csharp-mode")
(depends-on "yafolding")
(depends-on "omnisharp")
(depends-on "cmake-mode")
(depends-on "magit")
(depends-on "auto-org-md")
(depends-on "groovy-mode")
(depends-on "flycheck")
(depends-on "csproj-mode")
(depends-on "powershell")
(depends-on "request")
(depends-on "treemacs")

;;; (depends-on "arduino-mode")

(depends-on "js2-mode")
(depends-on "npm-mode")

(depends-on "exec-path-from-shell")
(depends-on "org-pomodoro")
(depends-on "sound-wav")

;;; Needed for helm
(depends-on "async")
(depends-on "popup")

;;; Helm & helm app
(depends-on "helm")
(depends-on "helm-projectile")
